### PR TITLE
Add ECDSA support for signed (secure) DFU.

### PR DESCRIPTION
**Pull request by carlescufi**
Includes:

* Adding a signature to the init packet
* Key handling

### CODE REVIEW

**Comment by carlescufi** [comment]
@hakonfam how is versioning supported now that all the code for older versions seems to have been removed? Can we still generate packages for older versions?

**Comment by hakonfam** [comment]
I have made no effort retaining compatibility with older package formats as its design is unsecure and should be deprecated. Since we produce LE data by default, and use a completely different serializing scheme, the current version will not be capable of generating packages for older formats.

**Comment by bihanssen** [comment]
@hakonfam is there a strategy for users that have deployed older dfu versions and want to upgrade to this new dfu version?

**Comment by hakonfam** [comment]
@bihanssen no, this is a decision that needs to be made by the product owner of the DFU project.

**Comment by bihanssen** [comment]
I am closing this PR until we have a clear strategy on how to handle or not handle backwards compatibility in nrfutil.

**Pull request closed without merging**
