### PR TITLE
Ensure same command name on different operating systems

### LINKED ISSUE #168: DFU commands over a USB serial connection are different between Windows and other OS
Althogh both of nrfutil are same version(4.0.0), the dfu command over a USB serial are different.
It is `nrfutil.exe dfu usb_serial` for Windows and is `nrfutil dfu usb-serial` for other OS.

### PR DESCRIPTION
**Pull request by bihanssen**
Command names with underscores have been observed to end up as hyphens on Windows and Mac, and underscores on Linux. Specifying the "name" property ensures correct naming.
Fixes #168.

### CODE REVIEW

**Comment by wingunder** [comment]
I think you should rename serial_usb to serial-usb, everywhere, in order to clear all confusion. See below:   
```
find . -type f |grep -v "\.git" |xargs grep usb_serial
./nordicsemi/__main__.py:def usb_serial(package, port, connect_delay, flow_control, packet_receipt_notification, baud_rate):
./README.md:##### usb_serial
./README.md:In the case of the nRF52840 development kit board, the `usb_serial` DFU mode is used when communicating with the board through the female USB port marked "nRF USB", which is wired
./README.md:nrfutil dfu usb_serial --help
./README.md:nrfutil dfu usb_serial -pkg app_dfu_package.zip -p COM3
```

**Comment by wingunder** [comment]
@bihanssen, Thanks for updating the README.md
Just a small naive question: Is there a reason why 6f61b97 must be part of this PR?

**Comment by bihanssen** [comment]
@wingunder The reason why 6f61b97 is part of the PR is explained in the commit message of fe9d3fd. It's related to a change in Click.

**Comment by wingunder** [comment]
@bihanssen, Perfect, thanks for the explanation.

**Pull request merged**
